### ISSUE TITLE
vm doesn't work

### ISSUE THREAD

**Issue by ghost** [argos-research/operating-system#1]
Hi,

I get the following error `sudo: make: command not found`

Moreover, `/build` is empty. @BugUser0815 @privatereese @Henni

**Comment by BugUser0815** [comment]
@dk87 a wrong path caused the error. Fixed.

**Comment by ghost** [comment]
no it runs. great @BugUser0815  @Henni @privatereese

**Comment by ghost** [comment]
test jenkins
