### ISSUE TITLE
missing event trigger

### ISSUE THREAD

**Issue by RobertHa** [argos-research/operating-system#26]
if a task is started by the period and destroys the instance that is still not finished  it is not triggering an exit event @BugUser0815

**Comment by BugUser0815** [comment]
@RobertHa please let me know if you get an Event::EXIT_EXTERNAL instead of nothing.

**Comment by RobertHa** [comment]
can we call it KILLED_BY_PERIOD ?

**Comment by BugUser0815** [comment]
Yes we can. Make Taskloader great again!

**Comment by RobertHa** [comment]
ah, i think i now like EXIT_PERIOD better
