### ISSUE TITLE
rework provision script

### ISSUE THREAD

**Issue by ghost** [argos-research/operating-system#4]
remove sudo commands where possible

**Comment by BugUser0815** [comment]
@privatereese I just uploaded the genode toolchain, which I need to close to this issue, to our nextcloud. Could you please share genode-gcc.tar.bz2 the same way you shared libports.tar.bz2?

**Comment by privatereese** [comment]
Done, https://nextcloud.os.in.tum.de/s/gh7Fal9KoV2kABe @BugUser0815
