### ISSUE TITLE
coupling of genode_Utilization and genode_AdmCtrl

### ISSUE THREAD

**Issue by ghost** [argos-research/operating-system#6]
Implementation of an interconnection (via monitor) between genode_Utilization and genode_AdmCtrl

**Comment by BugUser0815** [comment]
Note:
Feature is implemented and pushed, but not working on qemu.

**Comment by BugUser0815** [comment]
Note:
Use elapsed time and core idle to compute utilization.

**Comment by BugUser0815** [comment]
The synchronization of important tasks created this issue. Solved.
