### ISSUE TITLE
multicore affinity setting in runfile

### ISSUE THREAD

**Issue by ghost** [argos-research/operating-system#8]
for a comfortable configuration of components to core bindings - introduction of an affinity attribute in run files

**Comment by BugUser0815** [comment]
@dk87 whilst trying to implement this feature I discovered that it was already there.
Example file can be found here:
genode/repos/base/run/affinity_subspace.run

**Comment by ghost** [comment]
@BugUser0815 great, can we use it seamlessly with  our components or does we need to patch existing code?

**Comment by BugUser0815** [comment]
@dk87 it works as expected on real hardware. Unfortunately qemu becomes a burden more and more. Even though the Kconfig of pbxa9 says two cores, there seems to be only one core.
