### ISSUE TITLE
rework the interconnection between AdmCtrl and Synchronization (RQ Buffer)

### ISSUE THREAD

**Issue by ghost** [argos-research/operating-system#9]
The new workflow (e.g. for new task) results in the controller component as an active component rather than the synchronization component. Currently, the synchronization component actively requests the controller component for changes. To enable the new workflow, the controller component need to be the active part providing its changes to the synchronization component.

**Comment by BugUser0815** [comment]
Note:
Moving any interaction with the rq buffer into AdmCtrl removes shared dataspace issues with synchronization.
Shrink data exchange between AdmCtrl and Sync to tuples of id and prio of to be scheduled tasks.

**Comment by BugUser0815** [comment]
https://github.com/argos-research/genode-Synchronization/pull/1
https://github.com/argos-research/genode-AdmCtrl/pull/7
